### ISSUE TITLE
[Feature request] Send announcement to Discord server upon event creation using Webhooks

### ISSUE THREAD

**Issue by SVijayB** [Open-Source-Community-VIT-AP/OSC-API#5]
Refer to https://github.com/SVijayB/OSC-DBot/issues/20#issuecomment-988568136 for more details.

**Comment by SVijayB** [comment]
@officialakhil right now we are extracting data from postgresql database and as such we haven't implemented any POST request. Feel free to create an endpoint `/api/event/announcement` that triggers the webhook. Will add that to OSCHub upon event creation.

**Comment by officialakhil** [comment]
> @officialakhil right now we are extracting data from postgresql database and as such we haven't implemented any POST request. Feel free to create an endpoint `/api/event/announcement` that triggers the webhook. Will add that to OSCHub upon event creation.

Gotcha!
